'use client';

import React, { useState, useCallback } from 'react';
import { useDropzone } from 'react-dropzone';
import { useAccount, useSignMessage } from 'wagmi';
import { jsPDF } from 'jspdf'; // Библиотека для генерации PDF

const FileHasher = () => {
  const [fileHash, setFileHash] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [signature, setSignature] = useState<string | null>(null);
  const [isSigning, setIsSigning] = useState(false);

  const { address, isConnected } = useAccount();
  const { signMessageAsync } = useSignMessage();

  // 1. Хэширование
  const onDrop = useCallback((acceptedFiles: File[]) => {
    const file = acceptedFiles[0];
    setFileName(file.name);
    setSignature(null);

    const reader = new FileReader();
    reader.onload = async (e) => {
      const buffer = e.target?.result;
      if (buffer instanceof ArrayBuffer) {
        const hashBuffer = await crypto.subtle.digest('SHA-256', buffer);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
        setFileHash(`0x${hashHex}`);
      }
    };
    reader.readAsArrayBuffer(file);
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });

  // 2. Подпись
  const handleSign = async () => {
    if (!fileHash) return;
    setIsSigning(true);
    try {
      const message = `Я подтверждаю авторство файла:\nИмя: ${fileName}\nХэш: ${fileHash}\nДата: ${new Date().toISOString()}`;
      const sig = await signMessageAsync({ message });
      setSignature(sig);
    } catch (error) {
      console.error('Ошибка подписи:', error);
    }
    setIsSigning(false);
  };

  // 3. Генерация PDF
  const downloadCertificate = () => {
    if (!fileHash || !signature || !address) return;

    const doc = new jsPDF();
    const date = new Date().toLocaleString();

    // Дизайн сертификата
    doc.setLineWidth(1);
    doc.rect(10, 10, 190, 277); // Рамка
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.text("Certificate of Ownership", 105, 40, { align: "center" });

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Blockchain Timestamp Service", 105, 50, { align: "center" });

    doc.line(40, 60, 170, 60); // Линия разделителя

    // Основной текст
    doc.setFontSize(14);
    doc.text("This certifies that the file described below", 105, 80, { align: "center" });
    doc.text("was cryptographically signed by the owner.", 105, 88, { align: "center" });

    // Блок данных
    let y = 110;
    const lineHeight = 12;

    doc.setFont("courier", "bold");
    doc.text(`File Name:`, 20, y);
    doc.setFont("courier", "normal");
    doc.text(`${fileName}`, 60, y);
    
    y += lineHeight;
    doc.setFont("courier", "bold");
    doc.text(`Date:`, 20, y);
    doc.setFont("courier", "normal");
    doc.text(`${date}`, 60, y);

    y += lineHeight;
    doc.setFont("courier", "bold");
    doc.text(`Owner:`, 20, y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.text(`${address}`, 60, y);

    y += lineHeight * 2;
    doc.setFontSize(14);
    doc.setFont("courier", "bold");
    doc.text(`SHA-256 Hash:`, 20, y);
    y += 8;
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.text(`${fileHash}`, 20, y);

    y += lineHeight * 2;
    doc.setFontSize(14);
    doc.setFont("courier", "bold");
    doc.text(`Digital Signature:`, 20, y);
    y += 8;
    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    
    // Разбиваем длинную строку подписи, чтобы не вылезала за край
    const splitSig = doc.splitTextToSize(signature, 170);
    doc.text(splitSig, 20, y);

    // Подвал
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.text("Generated by CryptoNotary", 105, 280, { align: "center" });

    doc.save("Certificate.pdf");
  };

  return (
    <div className="space-y-6">
      {/* Дропзона */}
      {!fileHash ? (
        <div 
          {...getRootProps()} 
          className={`border-2 border-dashed rounded-2xl p-12 text-center transition cursor-pointer
            ${isDragActive ? 'border-blue-500 bg-blue-50' : 'border-gray-300 hover:border-blue-400 hover:bg-gray-50'}
          `}
        >
          <input {...getInputProps()} />
          <p className="text-gray-500 font-medium">Перетащи файл сюда или кликни</p>
        </div>
      ) : (
        <div className="p-6 bg-gray-50 rounded-2xl border border-gray-200 shadow-sm">
          <div className="flex justify-between items-center mb-4">
            <h3 className="font-bold text-gray-700 truncate max-w-[200px]">{fileName}</h3>
            <button 
              onClick={() => { setFileHash(null); setSignature(null); }}
              className="text-xs text-red-500 hover:underline"
            >
              Сбросить
            </button>
          </div>
          <div className="text-xs text-gray-500 break-all font-mono bg-white p-3 rounded border">
            {fileHash}
          </div>
        </div>
      )}

      {/* Кнопка подписи */}
      {fileHash && !signature && (
        <button
          onClick={handleSign}
          disabled={!isConnected || isSigning}
          className={`w-full py-3 rounded-xl font-bold text-white transition shadow-lg shadow-blue-500/30
            ${isConnected 
              ? 'bg-blue-600 hover:bg-blue-700 transform hover:scale-[1.02]' 
              : 'bg-gray-400 cursor-not-allowed'}
          `}
        >
          {isSigning ? 'Подписываем...' : isConnected ? 'Подписать кошельком' : 'Подключи кошелек'}
        </button>
      )}

      {/* Успех + Скачать PDF */}
      {signature && (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="bg-green-50 border border-green-200 rounded-2xl p-6 text-center space-y-4 shadow-sm">
            <div className="w-12 h-12 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto text-2xl">
              ✓
            </div>
            <h3 className="text-green-800 font-bold text-lg">Авторство подтверждено!</h3>
            
            <button
              onClick={downloadCertificate}
              className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 rounded-xl transition flex items-center justify-center gap-2 shadow-lg shadow-green-500/20 transform hover:scale-[1.02]"
            >
              <span>📄</span> Скачать Сертификат
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default FileHasher;